#!/usr/bin/Rscript


#create random indices from vector/data.frame, i.e 1,1,1,2,2,2,3,3,3,4,4,4,
createFoldIndices<-function(x,k){
  n <- nrow(x)
  folds <- rep(1:k,length.out = n)[sample(n,n,replace=F)]
  return(folds)
}

#creates stratified folds as data.frame "folds" with multiple columns
stratified_folds<-function(dat,k=5) {
	require(plyr)
	createFolds <- function(x,k){
	    n <- nrow(x)
	    x$folds <- rep(1:k,length.out = n)[sample(n,n)]
	    return(x)
	}	  
	true.presence<-dat[,length(dat)]
	folds <- ddply(dat,.(true.presence),createFolds,k = k)
	#Proportion of true.presence in each fold:
	cat("SUMMARY OF STRATIFIED FOLD CREATION\n")
	sum<-ddply(folds,.(folds),summarise,prop = sum(true.presence)/length(true.presence))
	print(sum)
	return(folds)
}

#creates random folds as data.frame "folds" with multiple columns
random_folds<-function(dat,k=5) {
  require(plyr)
  createFolds <- function(x,k){
    n<-nrow(x)
    #samples n numbers from 1 to k
    x$folds <- rep(1:k,length.out = n)[sample(n,n)]
    return(x)
  }	  
  folds<-createFolds(dat,k)
  folds<-data.frame(true.presence=dat[,length(dat)],folds)
  #Proportion of true.presence in each fold:
  #cat("SUMMARY OF RANDOM FOLD CREATION\n")
  #sum<-ddply(folds,.(folds),summarise,prop_mean = round(mean(true.presence)),sdev=round(sd(true.presence)))
  #print(sum)
  return(folds)
}

#returns the samples from the cv data.frame for fold n
return_fold<-function(df,n,test,retSparse=F) {
	if(test==FALSE){
	tmp<-df[df$folds!=n,]
	} else {
	tmp<-df[df$folds==n,]
	}
	rfold<- subset(tmp, select = -c(true.presence,folds) )
  if (retSparse) {
    rfold<-sparse.model.matrix(~ . - 1, data = rfold)
  }
	return(rfold)
}

#returns the indices from the cv data.frame for fold n
return_idx<-function(df,n,test) {
	if(test==FALSE){
	tmp<-df$folds!=n
	} else {
	tmp<-df$folds==n
	}
	return(tmp)
}

#returns list of train indices
leave_group_out_cv<-function(data,cv_labels) {
  cat("LGOCV...\n")
  data<-cbind(data,cv_labels=cv_labels)
  subs <- unique(data$cv_labels)
  train_idx_list <- vector(mode = "list", length = length(subs))
  for(i in seq_along(subs)) train_idx_list[[i]] <- which(data$cv_labels != subs[i])
  names(train_idx_list) <- paste0(subs,"")
  oinfo(train_idx_list)
  return(train_idx_list)
}

#returns cv folds from file generated by python
createFoldsFromFile<-function(filename,position=1,sep=";") {
  df<-read.csv(file=filename,sep=sep)
  #print(summary(df))
  return (df[,position])
}

saveFoldsToFile<-function(filename,x,k,n=1,sep=";") {
  for (i in 1:n) {
    if (i==1) {
      df<-data.frame(createFoldIndices(x,k))
    } else {
      df<-cbind(df,createFoldIndices(x,k))   
    }
    colnames(df)[i] <- paste0("fold",i)
  }
  #print(summary(df))
  write.table(df,file=filename,sep=sep,row.names=FALSE)
}







